form_story5/urls.py
from form_story5.views import tambah
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('story5/', views.schedule, name='schedule'),
    path('tambah/', views.tambah, name='tambah'),
    path('update/<str:param>/', views.update, name='update'),
    path('hapus/<str:param>/', views.hapus, name='hapus'),
    path('detail/<str:param>/', views.details, name='detail')
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('story1/', views.story1, name='story1'),
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.index, name='index'),
    path('interest/', views.interest, name='interest'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('gallery/', views.gallery, name='gallery'),
    path('credits/', views.credits, name='credits'),
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('form_story5.urls'))
]

form_story5/models.py
from django.db import models

# Create your models here.

class Schedule(models.Model):
    TERM = (
        ('Gasal 2019/2020', 'Gasal 2019/2020'),
        ('Genap 2019/2020', 'Genap 2019/2020'),
        ('Gasal 2020/2021', 'Gasal 2020/2021'),
        ('Genap 2020/2021', 'Genap 2020/2021'),
    )
    HARI = (
        ('Senin', 'Senin'),
        ('Selasa', 'Selasa'),
        ('Rabu', 'Rabu'),
        ('Kamis', 'Kamis'),
        ('Jumat', 'Jumat'),
    )
    matkul = models.CharField(max_length=100, null=True)
    sks = models.CharField(max_length=2, null=True)
    deskripsi = models.CharField(max_length=200, null=True)
    dosen = models.CharField(max_length=100, null=True)
    ruangan = models.CharField(max_length=100, null=True)
    term = models.CharField(max_length=100, null=True, choices=TERM)
    hari = models.CharField(max_length=10, null=True, choices=HARI, default='Senin')

    def __str__(self):
        return self.matkul

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

form_story5/forms.py
from django.forms import ModelForm
from .models import Schedule

class tambahForm(ModelForm):
    class Meta:
        model = Schedule
        fields = '__all__'

form_story5/views.py
from django.http import request
from django.shortcuts import render, redirect
from .models import *
from .forms import tambahForm

def schedule(request):
    schedule = Schedule.objects.all()
    return render(request, 'story5/form.html', {'schedule':schedule})

def matkul(request, param):
    schedule = Schedule.objects.get(matkul=param)
    return render(request, 'story5/form.html', {'schedule':schedule})

def tambah(request):
    form = tambahForm()

    if request.method == 'POST':
        form = tambahForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/story5/story5")

    context = {'form':form}
    return render(request, 'story5/tambah.html', context)

def update(request, param):
    schedule = Schedule.objects.get(id = param)
    form = tambahForm(instance=schedule)

    if request.method == 'POST':
        form = tambahForm(request.POST, instance=schedule)
        if form.is_valid():
            form.save()
            return redirect("/story5/story5")

    context = {'form':form}
    return render(request, 'story5/tambah.html', context)

def hapus(request, param):
    schedule = Schedule.objects.filter(id = param)
    matkul = Schedule.objects.get(id = param)
    if request.method == 'POST':
        schedule.delete()
        return redirect("/story5/story5")

    context = {'matkul':matkul}
    return render(request, 'story5/hapus.html', context)

def details(request, param):
    schedule = Schedule.objects.get(id = param)
    context = {'schedule':schedule}
    return render(request, 'story5/detail.html', context)

story1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'story1/story1.html')

story3/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story3/index.html')

def interest(request):
    return render(request, 'story3/interest.html')

def aboutme(request):
    return render(request, 'story3/aboutme.html')

def gallery(request):
    return render(request, 'story3/gallery.html')

def credits(request):
    return render(request, 'story3/credits.html')

form_story5/templates/story5/detail.html
<!doctype html>
<html lang="en">
  <head>
    {% extends 'story3/base.html' %}
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story5/style.css'%}">

    <title>Hello, world!</title>
  </head>
  <body>
    {% block content %}
    <table class="table">
        <tr>
            <td>Nama Mata Kuliah</td>
            <td>{{schedule.matkul}}</td>
        </tr>

        <tr>
            <td>Dosen Pengampu</td>
            <td>{{schedule.dosen}}</td>
        </tr>

        <tr>
            <td>Jumlah SKS</td>
            <td>{{schedule.sks}}</td>
        </tr>

        <tr>
            <td>Deskripsi Mata Kuliah</td>
            <td>{{schedule.deskripsi}}</td>
        </tr>

        <tr>
            <td>Term</td>
            <td>{{schedule.term}}</td>
        </tr>

        <tr>
            <td>Ruangan</td>
            <td>{{schedule.ruangan}}</td>
        </tr>
    </table>

    <a href={% url 'story5:schedule'%}>
        <button class="btn btn-outline-secondary">Kembali</button>
    <a>
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

form_story5/templates/story5/form.html
<!DOCTYPE html>
<html>
    {% extends 'story3/base.html' %}
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <title>Schedule</title>
    </head>

    <body>
        {% block content %}
        <table class="table">
            <tr>
                <th>Hari</th>
                <th>Matkul</th>
                <th>Total SKS</th>
                <th>Dosen</th>
                <th>Ruangan</th>
                <th>Update</th>
                <th>Hapus</th>
            </tr>

            {% for i in schedule %}
                <tr>
                    <td>{{i.hari}}</td>
                    <td><a id="matkul" href="{% url 'story5:detail' i.id%}">{{i.matkul}}</a></td>
                    <td>{{i.sks}}</td>
                    <td>{{i.dosen}}</td>
                    <td>{{i.ruangan}}</td>
                    <td>
                        <a href={% url 'story5:update' i.id %}>
                            <button class="btn btn-outline-info">Update Mata Kuliah</button>
                        <a>
                    </td>

                    <td>
                        <a href={% url 'story5:hapus' i.id %}>
                            <button class="btn btn-outline-danger">Hapus Mata Kuliah</button>
                        <a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <a href={% url 'story5:tambah'%}>
            <button class="btn btn-outline-secondary">Tambah Mata Kuliah</button>
        <a>
        {% endblock %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    </body>
</html>

form_story5/templates/story5/hapus.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <style>
            .konfirmasi {
                margin: auto;
            }
        </style>

        <title>Are you sure?</title>
    </head>

    <body>
        <div class="konfirmasi">
            <p>Hapus mata kuliah {{ matkul }} dari jadwal?</p>
            <form action="" method="POST">
                {% csrf_token %}
                <input class="btn btn-outline-primary" type="submit" name"confirm" value="Hapus"></input>
                <a class="btn btn-outline-danger" href={% url 'story5:schedule'%}>cancel</a>
            </form>
        </div>
         <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    </body>
</html>

form_story5/templates/story5/tambah.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <title>Tambah matkul</title>
    </head>

    <body>
        <form action="" method="POST">
            <table class="table">
                <tbody>
                    {{ form.as_table }}
                    <tr>
                        <th></th>
                        <td>
                            {% csrf_token %}
                            <button class="btn btn-outline-primary" type="submit" name="Simpan">Simpan</button>
                            <a class="btn btn-outline-danger" href="{% url 'story5:schedule'%}" name="Cancel">Cancel</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    </body>
</html>

story1/templates/story1/story1.html
<!DOCTYPE HTML>
<html>
    {% extends 'story3/base.html' %}
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Profil James</title>
        <link rel="stylesheet" href="{% static 'story1/style.css' %}">
    </head>

    <body>
        {% block content %}
        <div class="row">
            <div class="column_pics">
                <img src="{% static 'story1/1.jpeg' %}"/>
            </div>

            <div class="column">
                <hr size="3" noshade="" />
                <h1>James Frederix Rolianto</h1>
                <h3>1906398553</h3>
                <h3>2019 Computer Science Student, University of Indonesia</h3>
                <hr size="3" noshade="" />
                <h4>I want to be a future Data Scientist</h4>
                <hr size="3" noshade="" />

                <div>
                    <table>
                        <tr>
                            <td>My hobby : </td>
                            <td>- Watch a movie</td>
                        </tr>

                        <tr>
                            <td></td>
                            <td>- Riding</td>
                        </tr>

                        <tr>
                            <td></td>
                        </tr>

                        <tr>
                            <td></td>
                        </tr>

                        <tr>
                            <td>Education : </td>
                            <td>- SD Kwitang VIII PSKD</td>
                        </tr>

                        <tr>
                            <td></td>
                            <td>- SMP Negeri 13 Depok</td>
                        </tr>
                        
                        <tr>
                            <td></td>
                            <td>- SMA Negeri 9 Depok</td>
                        </tr>
                        
                        <tr>
                            <td></td>
                        </tr>

                        <tr>
                            <td></td>
                        </tr>

                        <tr>
                            <td>Experience : </td>
                            <td>- Badan Eksekutif Mahasiswa Universitas Indonesia (2020-now)</td>
                        </tr>

                        <tr>
                            <td></td>
                            <td>- Development Student Club Universitas Indonesia member (2019-now)</td>
                        </tr>

                        <tr>
                            <td></td>
                        </tr>

                        <tr>
                            <td></td>
                        </tr>

                        <tr>
                            <td>My Contact : </td>
                            <td><a href="https://www.instagram.com/james_frederix/">Instagram</a></td>
                        </tr>

                        <tr>
                            <td></td>
                            <td><a href="https://wa.me/+6281294503420?text=Hi,%20namaku%20[Nama],%20salam%20kenal%20ya!">WhatsApp</a></td>
                        </tr>

                        <tr>
                            <td></td>
                            <td><a href="http://line.me/ti/p/~shinoyajames">Line</a></td>
                        </tr>

                        <tr>
                            <td></td>
                            <td><a href="https://www.linkedin.com/in/james-frederix-rolianto-bb1100193/?originalSubdomain=id">LinkedIn</a></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        {% endblock %}
    </body>
</html>

story3/templates/story3/aboutme.html
<!DOCTYPE html>
<html>
    {% extends 'story3/base.html' %}
    {% load static %}
    <head>
         <!-- Required meta tags -->
         <meta charset="utf-8">
         <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
         <!-- Bootstrap CSS -->
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
 
         <link rel="stylesheet" href="{% static 'story3/style.css' %}"/>
         <title>About Me</title>
    </head>

    <body>
        {% block content %}
        <div class="col-sm">
            <div class="d-flex flex-row my-row row-kiri education">
                <div class="d-flex flex-column row-tiga">
                    <div class="p-2 judul">My Education</div>

                    <div class="p-2 list">
                        <ul>
                            <li>SD Kwitang 8 PSKD</li>
                            <li>SMP Negeri 13 Depok</li>
                            <li>SMA Negeri 9 Depok</li>
                        </ul>
                    </div>
                </div>
            </div>
        
            <div class="d-flex flex-row my-row row-kiri skills">
                <div class="d-flex flex-column row-tiga">
                    <div class="p-2 judul">My Skills</div>

                    <div class="p-2 list">
                        <ul>
                            <li>Python</li>
                            <li>Java</li>
                            <li>Public speaking</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm">
            <div class="d-flex flex-row my-row row-kanan bout-me">
                <div class="d-flex flex-column row-tiga">
                    <div class="p-2 judul">About Me</div>

                    <div class="p-2 list">
                        I was born in Depok and live in Depok since i was born. My MBTI is unique, 
                        sometimes it’s INFJ and sometimes it’s ENFJ. I am Computer Science student at University of Indonesia 
                        and I am Adkesma BEM UI staff.
                    </div>

                    <div class="p-2 list">
                        I want to be a Future data scientist.
                    </div>
                </div>
            </div>
        </div>

        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

story3/templates/story3/base.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head> 
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'story3/style.css'%}">
    </head>

    <body>
         <div class="navbar navbar-expand-lg navbar-light bg-light nav">
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navv">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navv">
                <ul class="navbar-nav ml-auto">
                    {% with url_name=request.resolver_match.url_name %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'story3:index'%}">Home</a>
                    </li>

                    <li class="nav-item {% if url_name == 'interest' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'story3:interest'%}">Interest</a>
                    </li>

                    <li class="nav-item {% if url_name == 'aboutme' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'story3:aboutme'%}">About Me</a>
                    </li>

                    <li class="nav-item {% if url_name == 'gallery' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'story3:gallery'%}">Activity Gallery</a>
                    </li>

                    <li class="nav-item {% if url_name == 'credits' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'story3:credits'%}">Credits</a>
                    </li>

                    <li class="nav-item {% if url_name == 'story1' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'story1:story1'%}">Story 1</a>
                    </li>

                    <li class="nav-item {% if url_name == 'schedule' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'story5:schedule'%}">Story 5</a>
                    </li>
                    {% endwith %}
                </ul>
            </div>
        </div>

        {% block content %}
        {% endblock %}

        <div class="footer lima">
            <table class="abc">
                <tr>
                    <td colspan="3">Find me at:</td>
                </tr>
                <tr>
                    <td>
                        <div class="contact">
                            <a href="https://www.instagram.com/james_frederix/">
                                <img class="contact" src="{% static 'story3/icons/ig.jpg' %}"/>
                            </a>
                        </div>
                    </td>

                    <td>
                        <div class="contact">
                            <a href="https://www.twitter.com/james_frederix/">
                                <img class="contact" src="{% static 'story3/icons/twt.jpg' %}"/>
                            </a>
                        </div>
                    </td>

                    <td>
                        <div class="contact">
                            <a href="https://id.linkedin.com/in/james-frederix-rolianto-bb1100193">
                                <img class="contact" src="{% static 'story3/icons/linkedin.jpg' %}"/>
                            </a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    </body>
</html>

story3/templates/story3/index.html
<!DOCTYPE html>
<html>
    {% extends 'story3/footer.html' %}
    {% load static %}
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'story3/style.css' %}"/>
        <title>Story 4 PPW</title>
    </head>

    <body>
        {% block content %}
        <div class="container profile">
            <div class="row">
                <div class="col prof-col">
                    <img src="{% static 'story3/icons/profile.jpg' %}" class="img-fluid prof-pic" alt="Responsive image"/>
                </div>

                <div class="col">
                    <div class="row">
                        <div class="name">James Frederix Rolianto</div>
                    </div>

                    <div class="row">
                        <div class="identity">
                            1906398553<br>
                            2019 Computer Science<br>
                            University of Indonesia
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container bawah">
            <div class="row depan">
                    <a href="{% url 'story3:interest'%}" class="col-sm" id="kiri">
                        <div class="bottom-right">Interest</div>
                    </a>

                    <a href="{% url 'story3:aboutme'%}" class="col-sm" id="tengah">
                        <div class="bottom-right">About Me</div>
                    </a>
                    
                    <a href="{% url 'story3:gallery'%}" class="col-sm" id="kanan">
                        <div class="bottom-right">Activity Gallery</div>
                    </a>
            </div>
        </div>

        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>